#!/bin/sh

RUN=$1
scp -P 2222 ./iloader.c root@localhost:/var/mobile/Documents/iloader/iloader.c;
scp -P 2222 ./iPhone3\,2/11D257/iBoot.h root@localhost:/var/mobile/Documents/iloader/iBoot.h;
scp -P 2222 ./iPhone3\,2/11D257/ramdisk.dmg root@localhost:/var/mobile/Documents/iloader/ramdisk.dmg;
if [ -z ${RUN+x} ]; then
	ssh root@localhsot -p 2222 "source /etc/profile; cd /var/mobile/Documents/iloader; make all; ./iloader";
else
ssh root@localhost -p 2222 "source /etc/profile; cd /var/mobile/Documents/iloader; make all";
fi